### ISSUE TITLE
Change root namespace to Windows.Detours to match win32metadata

### ISSUE THREAD

**Issue by 0x5bfa** [lowleveldesign/detours-win32metadata#4]
This package uses Microsoft.Detours iirc win32metadata also used but now it uses Windows.Win32 (wdkmetadata uses Windows.Wdk).
To be consistent id request to change the namespace.

https://github.com/lowleveldesign/detours-win32metadata/blob/58b585b58e79bad6e56165a4749ad93822cbbcd7/src/Detours.Win32Metadata.proj#L24

**Comment by 0x5bfa** [comment]
If approved, can I work on? It should be one-line change tho lol.

**Comment by lowleveldesign** [comment]
Thank you for the suggestion. However, I think that it does not make much sense to switch to Windows.Detours. For Windows.Win32 or Windows.Wdk, the Windows prefix makes perfect sense since both are wrapping Windows native APIs. Detours is not a system library, so I decided to use Microsoft as the root part of the namespace. And, who knows, maybe one day we will have support for Linux added to Detours? :slightly_smiling_face:

**Comment by 0x5bfa** [comment]
Ok i see you have clear insights on this. WhileI'd say i prefer Windows prefix since this is for Windows, I'm fine with this:)
